### PR TITLE
Feature/multi home

### PR DESCRIPTION
**Pull request by evonzee**
Hi, I had a need for multiple homes, so I've implemented it.  If you'd need to see more complete featureset before you'd accept this PR, like a mechanism to limit the number of homes a player can have if they're not admin, or a /homes command that lists their homes, I'll see what I can do.

### CODE REVIEW

**Comment by Thodde26** [comment]
Hi, Thx for that nice work. i will test it

**Comment by evonzee** [comment]
I added home listing and removal this morning.  I'm not planning on implementing a role-based limiter for my server for now; please let me know if that's something you'd need to have.

**Comment by Thodde26** [comment]
Hi, yes would be interesting, currently not yet but would be cool if times in the near future would give
sorry for my english

Best Regrades
Thodde26

**Comment by dmustanger** [comment]
has this been tested in a live environment?

**Comment by Thodde26** [comment]
Withe the change from evonzee the compiling works i will test it on my server
1>------ Erstellen gestartet: Projekt: ServerTools, Konfiguration: Release Any CPU ------
1>  ServerTools -> C:\Users\thodd\Desktop\7dtd-ServerTools-master\bin\Mods\ServerTools\ServerTools.dll
========== Erstellen: 1 erfolgreich, 0 fehlerhaft, 0 aktuell, 0 übersprungen ==========

**Comment by evonzee** [comment]
Thanks for merging.  I'm using it on my (small, private) server and no issues so far.  

I'll work on metering the amount of homes by role sometime this week.

**Pull request merged**
